Repository cobas67/Analysis_of_Subway_Data, pull requests merged in 2024-12, with the labels that each got.

#10 requirements.txt 파일 추가 및 기능구현
  requirments.txt
  station.py
Labels: enhancement

#18 README.md 파일작성, 최신 requirements.txt. 파일, 파이썬 코드 추가 합니다.
  README.md
  requirements.txt
  station.py
Labels: documentation

#22 머지개발 브랜치 병합 요청 /기존파일
  README.md
  station.py
Labels: duplicate

#23 경로 탐색 기능에 자신의 좌표를 출발역으로 하는 기능 추가 + 이동시간 및 거리 출력 추가
  Navi.py
  README.md
  station.py
Labels: documentation
